# Generated by Django 4.2.4 on 2023-08-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autonomous_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_history", models.JSONField(max_length=100000)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autonomous_app.business",
                    ),
                ),
            ],
        ),
    ]
